output "generated_files" {
  description = "Files generated by each module instance"

  value = {
    for environment, configuration in module.environment :
    environment => configuration.filename
  }
}