{
 "title": "DevOps Lab Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Linux 1-Minute Load Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{job=\"linux-node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\n  avg by (instance) (\n    rate(node_cpu_seconds_total{\n      job=\"linux-node\",\n      mode=\"idle\"\n    }[5m])\n  ) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  1 -\n  (\n    node_memory_MemAvailable_bytes{job=\"linux-node\"}\n    /\n    node_memory_MemTotal_bytes{job=\"linux-node\"}\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root Filesystem Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  1 -\n  (\n    node_filesystem_avail_bytes{\n      job=\"linux-node\",\n      mountpoint=\"/\"\n    }\n    /\n    node_filesystem_size_bytes{\n      job=\"linux-node\",\n      mountpoint=\"/\"\n    }\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target Availability",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  sum(up)\n  /\n  count(up)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}